name: Run Selenium Tests

on:
  workflow_dispatch:
    inputs:
      testng_xml:
        description: "Dynamic TestNG XML"
        required: true

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Print Base64
        run: |
          echo "----- BASE64 INPUT -----"
          echo "${{ github.event.inputs.testng_xml }}"

      - name: Decode XML
        run: |
          printf "%s" "${{ github.event.inputs.testng_xml }}" | base64 --decode > dynamic-testng.xml

      - name: Verify XML
        run: |
          echo "----- FILE SIZE -----"
          ls -lh dynamic-testng.xml
      
          echo "----- XML CONTENT -----"
          cat dynamic-testng.xml

      - name: Run tests
        run: |
          mvn test -Dsurefire.suiteXmlFiles=dynamic-testng.xml